version: "3"

networks:
  network_1:
  network_2:
  network_3:
  network_4:

services:
  # service for nginx
  nginx: 
    image: "nginx:server"
    container_name: nginx
    ports:
    - 8080:8080
    networks:
    - network_1
    - network_2
    - network_3
    - network_4
    restart: always

  # service for website 1
  website1:
    image: "website:1" 
    container_name: website-1
    expose:
      - 8001
    networks:
      - network_1
    environment:
      - MESSAGE="Hello Orient 1"
      - PORT=8001

  # service for website 2
  website2:
    image: "website:2"
    container_name: website-2
    expose:
      - 8002
    networks:
      - network_2
    environment:
      - MESSAGE="Hello Orient 2"
      - PORT=8002

  # service for website 3
  website3:
    image: "website:3" 
    container_name: website-3
    expose:
      - 8003
    networks:
      - network_3
    environment:
      - MESSAGE="Hello Orient 3"
      - PORT=8003

  # service for website 4
  website4:
    image: "website:4"
    container_name: website-4
    expose:
      - 8004
    networks:
      - network_4
    environment:
      - MESSAGE="Hello Orient 4"
      - PORT=8004